#!/usr/bin/env python3
"""Audit GitHub repository readiness and the minimal Pages deployment artifact."""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BASELINE_PATH = ROOT / 'audit' / 'RUNTIME_BASELINE_v0.1.6.json'
RUNTIME_FILES = (
    Path('index.html'), Path('styles.css'), Path('app.js'), Path('manifest.webmanifest'), Path('sw.template.js'), Path('sw.js'),
    Path('data/prayers.json'), Path('data/prayers.js'), Path('data/help.json'), Path('data/help.js'), Path('release.json'),
    Path('icons/icon.svg'), Path('icons/icon-192.png'), Path('icons/icon-512.png'),
)
PAGES_RUNTIME_FILES = tuple(item for item in RUNTIME_FILES if item != Path('sw.template.js'))
EXPECTED_SITE_FILES = set(PAGES_RUNTIME_FILES) | {Path('.nojekyll')}

EXPECTED_ACTION_PINS = {
    'actions/checkout': 'df4cb1c069e1874edd31b4311f1884172cec0e10',
    'actions/setup-node': '48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e',
    'actions/setup-python': 'a309ff8b426b58ec0e2a45f0f869d46889d02405',
    'actions/configure-pages': '983d7736d9b0ae728b81ab479565c72886d7745b',
    'actions/upload-pages-artifact': '7b1f4a764d45c48632c6b24a0339c27f5614fb0b',
    'actions/deploy-pages': 'd6db90164ac5ed86f2b6aed7e0febac5b3c0c03e',
}
FULL_SHA = re.compile(r'^[0-9a-f]{40}$')


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open('rb') as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b''):
            digest.update(block)
    return digest.hexdigest()


def parse_yaml(paths: list[Path]) -> list[str]:
    failures: list[str] = []
    ruby = "require 'yaml'; ARGV.each { |file| YAML.load_file(file) }; puts 'YAML: PASS'"
    command = ['ruby', '-e', ruby, *[str(path) for path in paths]]
    result = subprocess.run(command, cwd=ROOT, text=True, capture_output=True)
    if result.returncode:
        failures.append(f'YAML invalide : {(result.stdout + result.stderr).strip()}')
    return failures


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument('--site', help='Optional generated site directory to validate.')
    args = parser.parse_args()
    failures: list[str] = []
    required = [
        Path('.gitignore'), Path('NOTICE.md'), Path('requirements-dev.txt'), Path('docs/GITHUB_SETUP.md'),
        Path('.github/workflows/verify.yml'), Path('.github/workflows/deploy-pages.yml'),
        Path('tools/prepare_pages_site.py'), Path('tools/validate_pages_site.py'), Path('tools/build_github_package.py'),
        Path('tools/github_package_audit.py'), Path('tools/reopen_github_package_audit.py'), Path('tools/report_line_evidence.py'), Path('tools/release_identity.py'), Path('audit/GITHUB_SOURCE_PACKAGE_METADATA.json'), BASELINE_PATH,
    ]
    for path in required:
        if not path.is_file():
            failures.append(f'Fichier GitHub requis absent : {path}')

    package = json.loads((ROOT / 'package.json').read_text(encoding='utf-8'))
    scripts = package.get('scripts', {})
    for name in ['verify:ci', 'pages:prepare', 'pages:verify', 'github:verify', 'github:package', 'github:reopen-audit']:
        if name not in scripts:
            failures.append(f'Script npm requis absent : {name}')
    if 'github:package' in scripts and 'npm run github:verify' not in scripts['github:package']:
        failures.append('Le script github:package doit exécuter github:verify avant de créer un ZIP.')
    github_builder = ROOT / 'tools/build_github_package.py'
    if github_builder.is_file() and "tools/build_release.py" not in github_builder.read_text(encoding='utf-8'):
        failures.append('Le builder GitHub doit régénérer les manifestes de release avant de collecter les fichiers.')

    github_metadata_path = ROOT / 'audit/GITHUB_SOURCE_PACKAGE_METADATA.json'
    if github_metadata_path.is_file():
        github_metadata = json.loads(github_metadata_path.read_text(encoding='utf-8'))
        expected_github_metadata = {
            'schema': 'mes-prieres-github-source-package-v1',
            'repository_package_revision': 'R2-supply-chain-audited',
            'bundle_type': 'GitHub source-control package',
            'runtime_release_version': package['version'],
            'runtime_app_version': f"{package['version']}-help-audited-prototype",
            'runtime_baseline': 'audit/RUNTIME_BASELINE_v0.1.6.json',
            'embedded_private_release_evidence': 'audit/PACKAGE_METADATA.json',
            'deployment_artifact': 'site/ generated by tools/prepare_pages_site.py and excluded from this package',
            'build_script': 'tools/build_github_package.py',
            'reopen_audit_script': 'tools/reopen_github_package_audit.py',
        }
        for key, expected in expected_github_metadata.items():
            if github_metadata.get(key) != expected:
                failures.append(f'GitHub source metadata incohérent : {key}')

    if BASELINE_PATH.is_file():
        baseline = json.loads(BASELINE_PATH.read_text(encoding='utf-8'))
        if baseline.get('app_version') != f"{package['version']}-help-audited-prototype":
            failures.append('La baseline runtime ne correspond pas à la version app.')
        source_hash = baseline.get('source_release_sha256', '')
        if not isinstance(source_hash, str) or not re.fullmatch(r'[0-9a-f]{64}', source_hash):
            failures.append('La baseline runtime ne contient pas un SHA-256 de release source exploitable.')
        if baseline.get('source_release_bytes') != 97329:
            failures.append('La baseline runtime ne contient pas la taille vérifiée de la release source v0.1.6.')
        hashes = baseline.get('runtime_files', {})
        if set(hashes) != {path.as_posix() for path in RUNTIME_FILES}:
            failures.append('La baseline runtime ne couvre pas exactement les fichiers runtime attendus.')
        for relative in RUNTIME_FILES:
            actual = sha256(ROOT / relative)
            if hashes.get(relative.as_posix()) != actual:
                failures.append(f'Runtime modifié par rapport à la baseline audité v0.1.6 : {relative}')

    workflow_paths = [ROOT / '.github/workflows/verify.yml', ROOT / '.github/workflows/deploy-pages.yml']
    failures.extend(parse_yaml(workflow_paths))
    if all(path.is_file() for path in workflow_paths):
        verify = workflow_paths[0].read_text(encoding='utf-8')
        deploy = workflow_paths[1].read_text(encoding='utf-8')
        for token in ['pull_request:', 'push:', 'npm run github:verify']:
            if token not in verify:
                failures.append(f'Workflow de vérification incomplet : {token}')
        for token in ['workflow_dispatch:', 'confirm_public_pages:', 'path: site', 'include-hidden-files: true', 'name: github-pages']:
            if token not in deploy:
                failures.append(f'Workflow Pages incomplet : {token}')
        combined_workflows = verify + '\n' + deploy
        action_refs = re.findall(r'uses:\s*([A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+)@([A-Za-z0-9_.-]+)', combined_workflows)
        for action, expected_sha in EXPECTED_ACTION_PINS.items():
            matching_refs = [ref for found_action, ref in action_refs if found_action == action]
            if not matching_refs:
                failures.append(f'Action GitHub requise absente : {action}')
            for actual_ref in matching_refs:
                if actual_ref != expected_sha:
                    failures.append(f'Action GitHub non épinglée au SHA attendu : {action}@{actual_ref}')
        for action, ref in action_refs:
            if not FULL_SHA.fullmatch(ref):
                failures.append(f'Action GitHub référencée par une ref mutable : {action}@{ref}')
        if re.search(r'^\s*push:', deploy, flags=re.MULTILINE):
            failures.append('Le workflow Pages ne doit pas déployer automatiquement sur push.')
        if "inputs.confirm_public_pages == true" not in deploy:
            failures.append('Le workflow Pages doit exiger une confirmation explicite avant le build.')

    readme = (ROOT / 'README.md').read_text(encoding='utf-8')
    setup = (ROOT / 'docs/GITHUB_SETUP.md').read_text(encoding='utf-8')
    qa_report = (ROOT / 'audit/QA_REPORT.md').read_text(encoding='utf-8')
    four_pass = (ROOT / 'audit/FOUR_PASS_AUDIT.md').read_text(encoding='utf-8')
    active_reports = '\n'.join([readme, qa_report, four_pass, (ROOT / 'docs/CORPUS_STATUS.md').read_text(encoding='utf-8')])
    if 'no public-release workflow' in active_reports.lower():
        failures.append('Rapport actif obsolète : il nie l’existence du workflow Pages manuel.')
    if 'manual, confirmation-gated Pages workflow' not in qa_report or 'manual confirmation-gated Pages workflow' not in four_pass:
        failures.append('Les rapports actifs ne bornent pas correctement le workflow Pages manuel.')
    for phrase in ['GitHub Pages', 'publique', 'ne pas', 'npm run github:verify', 'full commit SHA']:
        if phrase not in readme + setup:
            failures.append(f'Documentation GitHub/livraison insuffisante : {phrase}')
    for phrase in ['release.json', 'vérifier les mises à jour', 'version installée']:
        if phrase not in readme.lower() + setup.lower():
            failures.append(f'Documentation de mise à jour insuffisante : {phrase}')
    if not re.search(r'GitHub Pages sites are\s+publicly reachable', setup):
        failures.append('La documentation ne signale pas clairement le risque de publication Pages.')
    if 'repository-audit revision' not in setup.lower():
        failures.append('La documentation ne distingue pas la révision du package GitHub de la version runtime.')

    if args.site:
        site = Path(args.site).resolve()
        if not site.is_dir():
            failures.append('Dossier site absent pour audit GitHub.')
        else:
            actual = {path.relative_to(site) for path in site.rglob('*') if path.is_file()}
            if actual != EXPECTED_SITE_FILES:
                failures.append('Le dossier site ne contient pas exactement le runtime autorisé.')
            for relative in PAGES_RUNTIME_FILES:
                if not (site / relative).is_file() or sha256(site / relative) != sha256(ROOT / relative):
                    failures.append(f'Le site déployable diffère du runtime source : {relative}')
            prohibited_prefixes = ('audit/', 'docs/', 'tests/', 'tools/', '.github/')
            if any(item.as_posix().startswith(prohibited_prefixes) for item in actual):
                failures.append('Le site déployable expose des fichiers internes.')

    if failures:
        print('GITHUB_PACKAGE_AUDIT: FAIL')
        for failure in failures:
            print(f'- {failure}')
        return 1
    print('GITHUB_PACKAGE_AUDIT: PASS')
    print(f'App runtime baseline: v{package["version"]}')
    print('Pages deployment: manual confirmation required')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
